name: Website

# Netlify builds the website for PRs, so this workflow is probably
# unnecessary except on push to the `main` branch.

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'website/**'
      - 'packages/**'
  push:
    branches: [main]
    paths:
      - 'website/**'
      - 'packages/**'

env:
  NODE_OPTIONS: --max-old-space-size=4096
  YARN_ENABLE_IMMUTABLE_INSTALLS: false

jobs:
  build_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: oven-sh/setup-bun@v1
        # We use Yarn to install dependencies because of https://github.com/oven-sh/bun/issues/2257.
        # When that's fixed, we can just do `bun install` here (perhaps with `--frozen-lockfile`)
        # and remove the subsequent three Yarn-related steps.
      - run: bun install --yarn --dry-run
      - run: bun ./website/update-yarn.lock.ts
      - run: yarn set version berry
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn
      - run: bun run build
      - run: bun run website:build
        # The following deployment steps only run when pushing to the `main` branch
      - name: Setup SSH
        if: github.event_name != 'pull_request'
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_WEBSITE_DEPLOY }}
      - name: Deploy website to GitHub Pages
        if: github.event_name != 'pull_request'
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          git config --global user.email ${{ secrets.GH_PAGES_WEBSITE_PUBLISHER_EMAIL }}
          git config --global user.name ${{ secrets.GH_PAGES_WEBSITE_PUBLISHER_NAME }}
          yarn run website:deploy
