name: Website

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'website/**'
  push:
    branches: [main]
    paths:
      - 'website/**'

env:
  NODE_OPTIONS: --max-old-space-size=4096

jobs:
  build_setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Use Bun to generate yarn.lock
        # We use Yarn to install dependencies because of
        # https://github.com/oven-sh/bun/issues/2257
        # When this is fixed, we can just do `bun install`, perhaps with `--frozen-lockfile`
        run: bun install --yarn --dry-run
      - name: Prepare yarn.lock for Yarn berry upgrade
        run: bun ./website/update-yarn.lock.ts
      - name: Upgrade to Yarn berry
        run: yarn set version berry
      - name: Install dependencies with Yarn
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn
      - name: Build packages
        run: bun run build
      - name: Build website
        run: bun website:build

  # Netlify builds the website for PRs, so this job is probably unnecessary.
  build_only:
    if: github.event_name != 'push' || github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build_setup

  build_and_publish:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: build_setup
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_WEBSITE_DEPLOY }}
      - name: Deploy website to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          git config --global user.email ${{ secrets.GH_PAGES_WEBSITE_PUBLISHER_EMAIL }}
          git config --global user.name ${{ secrets.GH_PAGES_WEBSITE_PUBLISHER_NAME }}
          yarn run website:deploy
